version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: parcial_v2_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0006"
      POSTGRES_DB: parcial_v2

    ports:
      - "5435:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: