@baseUrl = http://localhost:8000
@json = application/json


### ==========================================
### MÓDULO: CATEGORÍAS
### ==========================================

### Crear Categoria
POST {{baseUrl}}/categorias/
Content-Type: {{json}}

{
  "nombre": "Hamburguesas",
  "descripcion": "Todo tipo de hamburguesas",
  "imagen_url": "https://foodish-api.com/images/burger/burger32.jpg"
}

### Crear Categoria 2
POST {{baseUrl}}/categorias/
Content-Type: {{json}}

{
  "nombre": "Pizzas",
  "descripcion": "Todo tipo de pizzas",
  "imagen_url": "hhttps://foodish-api.com/images/pizza/pizza2.jpg"
}

### Crear Categoria con id padre
POST {{baseUrl}}/categorias/
Content-Type: {{json}}

{
  "nombre": "Hambuerguesas veganas",
  "descripcion": "Hamburguesas libre de carne animal",
  "imagen_url": "https://foodish-api.com/images/burger/burger35.jpg",
  "parent_id": 1
}

### Crear Categoria con id padre
POST {{baseUrl}}/categorias/
Content-Type: {{json}}

{
  "nombre": "Hambuerguesas smash",
  "descripcion": "Hamburguesas smasheadas de carne",
  "imagen_url": "https://foodish-api.com/images/burger/burger3.jpg",
  "parent_id": 1
}

### Listar todas las Categorias
GET {{baseUrl}}/categorias/

### Listar las Categorias con query
GET {{baseUrl}}/categorias/?offset=0&limit=10

### Listar todas las Categorias ordenadas por categoria padre
GET {{baseUrl}}/categorias/tree

### Detalle de una Categoria
GET {{baseUrl}}/categorias/2

### Actualizar una Categoria
PATCH {{baseUrl}}/categorias/3
Content-Type: {{json}}

{
  "nombre": "Hambuerguesas de pollo",
  "descripcion": "Hamburguesas con carne de pollo",
  "imagen_url": "https://foodish-api.com/images/burger/burger2.jpg",
  "parent_id": 1
}

### Desactivar Categoria (Borrado logico)
DELETE {{baseUrl}}/categorias/3


### ==========================================
### MÓDULO: INGREDIENTES
### ==========================================

### Crear ingrediente
POST {{baseUrl}}/ingredientes/
Content-Type: {{json}}

{
  "nombre": "Carne",
  "descripcion": "carne de vaca"
}

### Crear ingrediente alergeno (no apto para celiacos)
POST {{baseUrl}}/ingredientes/
Content-Type: {{json}}

{
  "nombre": "Pan",
  "descripcion": "pan de papa",
  "es_alergeno": true
}

### Crear ingrediente no alergeno
POST {{baseUrl}}/ingredientes/
Content-Type: {{json}}

{
  "nombre": "Pepinillo",
  "descripcion": "pepinos agrios",
  "es_alergeno": false
}

### Crear ingrediente no alergeno 2
POST {{baseUrl}}/ingredientes/
Content-Type: {{json}}

{
  "nombre": "Salsa",
  "descripcion": "Salsa de tomate",
  "es_alergeno": false
}

### Crear ingrediente no alergeno 3
POST {{baseUrl}}/ingredientes/
Content-Type: {{json}}

{
  "nombre": "Queso",
  "descripcion": "Queso cremoso",
  "es_alergeno": false
}

### Listar ingredientes
GET {{baseUrl}}/ingredientes/

### Listar ingredientes query
GET {{baseUrl}}/ingredientes/?offset=0&limit=10&nombre=pan

### Detalle de ingrediente
GET {{baseUrl}}/ingredientes/1

### Actualizar ingrediente
PATCH {{baseUrl}}/ingredientes/2
Content-Type: {{json}}

{
  "nombre": "Pan con moras",
  "descripcion": "pan de papa con moras",
  "es_alergeno": true
}

### Desactivar ingrediente (Borrado logico)
DELETE {{baseUrl}}/ingredientes/2

### ==========================================
### MÓDULO: PRODUCTOS
### ==========================================

### Crear Producto
POST {{baseUrl}}/productos/
Content-Type: {{json}}

{
  "nombre": "Hamburguesa simple BIG",
  "unidad_medida_id":5,
  "descripcion": "Hamburguesa con queso, tomate, lechuga, cebolla y pepinillos",
  "precio_base": 250.00,
  "imagenes_url":[
  "https://foodish-api.com/images/burger/burger5.jpg",
  "https://foodish-api.com/images/burger/burger4.jpg"],
  "stock_cantidad":10,
  "disponible": true,
  "categorias":[
    {"id":1,
      "es_principal":false
    },
    {"id":3,
      "es_principal":true
    }
  ],
  "ingredientes":[
    {"id":1,
      "cantidad":150,
      "unidad_medida_id": 2,
      "es_removible":false
    },
    {"id":2,
      "cantidad":1,
      "unidad_medida_id": 5,
      "es_removible":false
    },
    {"id":3,
      "cantidad":2,
      "unidad_medida_id": 5,
      "es_removible":true
    }

  ]
}

### Crear Producto
POST {{baseUrl}}/productos/
Content-Type: {{json}}

{
  "nombre": "Pizza muzza",
  "unidad_medida_id":5,
  "descripcion": "Pizza muzzarela, queso y salsa",
  "precio_base": 100.00,
  "imagenes_url":[
  "https://foodish-api.com/images/pizza/pizza1.jpg"],
  "stock_cantidad":10,
  "disponible": true,
  "categorias":[
    {"id":2,
      "es_principal":true
    }
  ],
  "ingredientes":[
    {"id":4,
      "cantidad":250,
      "unidad_medida_id": 4,
      "es_removible":false
    },
    {"id":5,
      "cantidad":200,
      "unidad_medida_id": 2,
      "es_removible":true
    }

  ]
}

### Listar Productos
GET {{baseUrl}}/productos/

### Listar Productos, solo 5 en este caso
GET {{baseUrl}}/productos/?offset=0&limit=5

### Detalle Producto
GET {{baseUrl}}/productos/1

### Actualizar Producto
PATCH {{baseUrl}}/productos/2
Content-Type: {{json}}

{
  "nombre": "Hamburguesa simple BIG",
  "unidad_medida_id":5,
  "descripcion": "Hamburguesa con queso, tomate y lechuga",
  "precio_base": 250.00,
  "imagenes_url":[
  "https://foodish-api.com/images/burger/burger6.jpg",
  "https://foodish-api.com/images/burger/burger4.jpg"],
  "stock_cantidad":10,
  "disponible": true,
  "categorias":[
    {"id":1,
      "es_principal":false
    },
    {"id":3,
      "es_principal":true
    }
  ],
  "ingredientes":[
    {"id":1,
      "cantidad":150,
      "unidad_medida_id": 2,
      "es_removible":false
    },
    {"id":2,
      "cantidad":1,
      "unidad_medida_id": 5,
      "es_removible":false
    }
  ]
}


### Desactivar Producto
DELETE {{baseUrl}}/productos/1

### ==========================================
### MÓDULO: PEDIDO
### ==========================================

### Crear un Pedido
POST {{baseUrl}}/pedidos/
Content-Type: {{json}}

{
  "direccion_id": 1,
  "forma_pago_codigo": "EFECTIVO",
  "descuento": 10,
  "costo_envio": 50,
  "notas": "PONEME SERVILLETAS PORFAVOR",
  "detalle_pedidos": [
     {
      "producto_id": 1,
      "cantidad": 2,
      "personalizacion":[3]
     },
     {
      "producto_id": 2,
      "cantidad": 2,
      "personalizacion":[]
     }
    ]
}

### Obtener Pedidos
GET {{baseUrl}}/pedidos

### Obtener un Pedido
GET {{baseUrl}}/pedidos/1

### Avanzar Estado
PATCH {{baseUrl}}/pedidos/1
Content-Type: {{json}}

{
  "estado_bool": true,
  "motivo": ""
}

### Cancelar Estado
PATCH {{baseUrl}}/pedidos/1
Content-Type: {{json}}

{
  "estado_bool": false,
  "motivo": "PORQUE SI"
}

### Eliminnar Pedido
DELETE {{baseUrl}}/pedidos/1